load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
	name = "main",
	srcs = ["main.cc"],
	deps = [
	#"child/name",
#	    "//src/lib:constants",
            "//src/lib/dio:dio",
        ],
)

#cc_library(
#	name = "",
#	srcs = [""],
#	hdrs = [""],
#)
