cc_library(
    name = "dio",
    srcs = ["dio.cc"],
    hdrs = ["dio.h"],
    deps = [
        "//third_party/WiringPi:wiringpi",
        "//src/lib:constants"
    ],
    visibility = ["//visibility:public"],
)
